[phases.setup]
nixPkgs = ["nodejs_21"]

[phases.install]
cmds = [
  "(cd backend && npm ci --production)",
  "(cd frontend && npm ci)"
]

[phases.build]
cmds = [
  "(cd frontend && npm run build)"
]

[start]
cmd = "cd backend && node src/server.js"
