[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd backend && npm ci --production",
  "cd frontend && npm ci && npm run build"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && node src/server.js"
